# Generated by Django 3.2 on 2022-04-19 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='quantity',
            options={'verbose_name_plural': 'Quantities'},
        ),
        migrations.AlterField(
            model_name='quantity',
            name='count',
            field=models.CharField(blank=True, default='1', max_length=2),
        ),
    ]
