# Generated by Django 3.2.5 on 2021-07-02 12:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quantity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.PositiveIntegerField()),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.menuitem')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.ordermodel')),
            ],
        ),

        migrations.RemoveField(
            model_name='ordermodel',
            name='items'
        ),

        migrations.AddField(
            model_name='ordermodel',
            name='items',
            field=models.ManyToManyField(blank=True, related_name='order', through='customer.Quantity', to='customer.MenuItem'),
        ),

    ]
