# Generated by Django 3.2.5 on 2021-07-02 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_auto_20210702_1802'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quantity',
            name='count',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
