# Generated by Django 3.2 on 2022-04-18 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_auto_20210414_1205'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='prep_time',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=2, null=True),
        ),
        migrations.AddField(
            model_name='ordermodel',
            name='wait_time',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=2, null=True),
        ),
    ]
