# Generated by Django 3.2 on 2022-04-18 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_auto_20220418_1726'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='prep_time',
            field=models.DecimalField(decimal_places=2, max_digits=2, null=True),
        ),
        migrations.AlterField(
            model_name='ordermodel',
            name='wait_time',
            field=models.DecimalField(decimal_places=2, max_digits=2, null=True),
        ),
    ]
