# Generated by Django 3.2.5 on 2021-07-02 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_alter_quantity_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quantity',
            name='count',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
