# Generated by Django 3.2.5 on 2021-07-02 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0005_alter_quantity_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quantity',
            name='count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
