# Generated by Django 3.2 on 2022-04-18 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0005_auto_20220418_1730'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ordermodel',
            old_name='wait_time',
            new_name='time',
        ),
    ]
